user_helper:
  size: 80
avatar:
  size: 50
validates:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
session_controller:
  session: 1
show_limit:
  show_10: 10
password_reset_expired:
  time: 2
picture:
  size: 5
image:
  resize_width_limit: 400
  resize_height_limit: 400
content_maximum: 140
